command = "touch"

[[match_err]]
pattern = [ "no such file or directory" ]
suggest = [
'''
#[!shell(nu)]
mkdir -p {{cmd::(?:\s)+(.*[\\\/])(?:\s)*}} &&
touch {{command[1:]}} '''
]

[[match_err]]
pattern = [
	"nu::shell::create_not_possible",
	"no such file or directory",
]
suggest = [
'''
#[shell(nu)]
mkdir {{cmd::(?:\s)+(.*[\\\/])(?:\s)*}};
touch {{command[1:]}} '''
]
